lr0: 0.003            # Lower learning rate for finer convergence
lrf: 0.01
momentum: 0.94
weight_decay: 0.0008
warmup_epochs: 3.0
warmup_momentum: 0.85
warmup_bias_lr: 0.05

# Loss weights
box: 0.07             # Slightly more box regression focus
cls: 0.5              # Still modest due to binary classification
cls_pw: 1.0
obj: 3.0              # 🔺 Increase objectness to fight false negatives
obj_pw: 2.0
iou_t: 0.15           # Loosen IoU threshold – encourages detection of low-overlap cases
anchor_t: 4.0
fl_gamma: 1.5         # 🔺 Add Focal Loss to downweight easy examples & focus on hard ones

# Color & Geometry Augmentations
hsv_h: 0.02
hsv_s: 0.4
hsv_v: 0.3
degrees: 3.0
translate: 0.07
scale: 0.4
shear: 0.5
perspective: 0.002

# Flips & Cutout
flipud: 0.1
fliplr: 0.5
mosaic: 1.0
mixup: 0.15
copy_paste: 0.15
