lr0: 0.007             # ⚠️ Slightly reduced to prevent overshooting minima on small datasets
lrf: 0.05
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 2.0     # ⚠️ Less warmup since you're converging very quickly
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Loss balancing
box: 0.05
cls: 0.6              # ⚠️ Slightly down – your data is effectively single-class (background vs infected)
cls_pw: 1.0
obj: 2               # ⚠️ Slightly increased to reduce false negatives for tiny crescents
obj_pw: 1.5
iou_t: 0.2
anchor_t: 5.0
fl_gamma: 0.0

# Color & Geometry Augmentations
hsv_h: 0.03            # ⚠️ Slightly less hue jitter – minimize color distortion for biomedical consistency
hsv_s: 0.6
hsv_v: 0.4
degrees: 5.0           # ⚠️ Reduce from 10.0 – medical cell shape matters
translate: 0.05        # ⚠️ Minor positional jitter is enough
scale: 0.5            # ⚠️ Reduce zoom variation for better bbox regression
shear: 1.0             # ⚠️ Reduce distortion
perspective: 0.001

# Flips & Cutout
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.2             # ⚠️ Re-enabled gently – helps generalize with ~0.1 on clean data
copy_paste: 0.2

flipud: 0.1
