lr0: 0.007
lrf: 0.05
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 2.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.6
cls_pw: 1.0
obj: 2
obj_pw: 1.0
iou_t: 0.3
anchor_t: 3.0
fl_gamma: 0.0
hsv_h: 0.03
hsv_s: 0.6
hsv_v: 0.4
degrees: 5.0
translate: 0.05
scale: 0.4
shear: 1.0
perspective: 0.0005
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.1
copy_paste: 0.1
